# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e7c39e06025d2a7868b4da229eeaf3310ac924cadb1a78e140f0447fe4432a6532ce8d7e67eb5013407cbd83794c9db305429f2d614033c8e888cd70025b6000

test:
  secret_key_base: a59c53c5579a45cf222069e6c31330dc8cb3b23bd917475fabd7743a34030b47368790ad07e149a5e0138bc33b5caa1ed66f6598e8516d2f5a38ea316a3294f4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
